### ISSUE TITLE
组件里有个变量_data_是在哪里定义的?

### ISSUE THREAD

**Issue by sonicsunsky** [ChanceYu/weapp#1]
这里的这个_data_在哪里定义的，怎么找不到_data_的声明和定义呢???

如:
`<view class="weapp-city-picker">
    <picker mode="region" bindchange="WeApp_CityPicker_Change" data-component-id="{{_data_.id}}" value="{{_data_.region}}">
      <view>
        {{_data_.showLabel}}
      </view>
    </picker>
  </view>`

**Comment by sonicsunsky** [comment]
去掉_data_好像不可以，但是_data_在项目的代码里确实是找不到呀，求助

**Comment by ChanceYu** [comment]
所有的`_data_`是在页面调用组件模板的时候传递的，例如Tab组件使用：`<template is="weapp-tab" data="{{ _data_: oTab1 }}"></template>`，参考页面pages/weapp/tab

**Comment by sonicsunsky** [comment]
哦哦，是在调用组件模板使用template标签的时候定义的呀，那_data_可以换成其它的标识符喽，如mydata或者__data等变量名
