### ISSUE TITLE
calendarPicker里面的font-awesome icons显示不出来

### ISSUE THREAD

**Issue by Will3000** [ChanceYu/weapp#8]
新版小程序里面自定义的components好像都用不了font-awesome icons。 如果我直接在caldendarPick.wxss `@import "/components/libs/font-awesome/font-awesome.wxss"; `就会出现以下错误：

VM2542:2 Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute selectors.(./components/calendarPicker/calendarPicker.wxss:150:1)This wxss file is ignored.

**Comment by ChanceYu** [comment]
font-awesome.wxss 里面多了下面这样的css语法

![image](https://user-images.githubusercontent.com/12869521/43496911-5ea1d3f8-9572-11e8-9504-53538c345ea8.png)
小程序里面有些选择器不支持可能会报这样的错误，已经修改 font-awesome.wxss

**Comment by Will3000** [comment]
感谢大大
